version: 2
jobs:
  build:
    environment:
      PLUGIN_CODE: "Taba2FA"
      DBSERVER: 127.0.0.1
      DBNAME: cube3_dev
      DBUSER: cube3_dev_user
      DBPASS: password

    branches:
      only:
        - master

    docker:
      - image: circleci/php:5.6-apache-node-browsers
      - image: circleci/mysql:5.5
        command: |
          mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: cube3_dev
          MYSQL_USER: cube3_dev_user
          MYSQL_PASSWORD : password
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: no
      - image: circleci/postgres:9.3-ram
        environment:  
          POSTGRES_DB: cube3_dev
          POSTGRES_USER: cube3_dev_user
          POSTGRES_PASSWORD : password

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: Wait for database
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name:  Install PHP module 
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            sudo apt install -y mysql-client
            sudo docker-php-ext-install pdo_mysql
            sudo apt-get -y install zlib1g-dev libpq-dev
            sudo docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
            sudo docker-php-ext-install pdo_pgsql
            sudo apt install -y postgresql-client || true

      - run:
          name: Package the plugin 
          command: |
            cd $HOME/repo
            tar zcvf $HOME/$PLUGIN_CODE.tar.gz *

      - run:
          name: Checkout EC-CUBE 
          command: |
            cd $HOME
            git clone --branch master https://github.com/EC-CUBE/ec-cube.git
            cd $HOME/ec-cube
            git checkout -b refs/tags/3.0.16

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "~/ec-cube/composer.json" }}
          - v1-dependencies-

      - run:
          name: Composer init
          command: |
            cd $HOME/ec-cube
            composer selfupdate
            composer global require hirak/prestissimo
            composer install --dev --no-interaction -o

      - save_cache: 
          paths:
            - ~/ec-cube/vendor
          key: v1-dependencies-{{ checksum "~/ec-cube/composer.json" }}

      - run:
          name: Install EC-CUBE  using MySQL 
          command: |
            cd $HOME/ec-cube
            cp $HOME/repo/.circleci/eccube_install.sh .
            sh ./eccube_install.sh mysql

      - run:
          name: Install plugin
          command: |
            cd $HOME/ec-cube
            php app/console plugin:develop install --path=$HOME/$PLUGIN_CODE.tar.gz
            php app/console plugin:develop enable --code=$PLUGIN_CODE
            php app/console plugin:develop disable --code=$PLUGIN_CODE
            php app/console plugin:develop uninstall --code=$PLUGIN_CODE
            rm -rf app/Plugin/$PLUGIN_CODE
            rm -rf app/cahce/*

      - run:
          name: Install EC-CUBE  using PostgreSQL 
          command: |
            cd $HOME/ec-cube
            cp $HOME/repo/.circleci/eccube_install.sh .
            sh ./eccube_install.sh pgsql

      - run:
          name: Install plugin
          command: |
            cd $HOME/ec-cube
            php app/console plugin:develop install --path=$HOME/$PLUGIN_CODE.tar.gz
            php app/console plugin:develop enable --code=$PLUGIN_CODE
            php app/console plugin:develop disable --code=$PLUGIN_CODE
            php app/console plugin:develop uninstall --code=$PLUGIN_CODE
            rm -rf app/Plugin/$PLUGIN_CODE
            rm -rf app/cahce/*
