version: 2
jobs:
  build:
    environment:
      PLUGIN_CODE: "Taba2FA"

    branches:
      only:
        - master

    docker:
      # https://hub.docker.com/r/circleci/php/tags/
      # https://hub.docker.com/r/circleci/mysql/tags/
      - image: circleci/php:5.6-apache-node-browsers
      - image: circleci/mysql:5.5

    environment:
      DB_HOST: 127.0.0.1
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "testpassword"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./ec-cube/vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      #- run: phpunit

      - run:
          name: prepare
          command: |
            tar zcvf ~/$PLUGIN_CODE.tar.gz *

            export DBSERVER=$DB_HOST
            export DBNAME=testdb
            export DBUSER=$MYSQL_USER
            export DBPASS=$MYSQL_PASSWORD

            git clone --branch master https://github.com/EC-CUBE/ec-cube.git
            cd ec-cube
            git checkout -b refs/tags/3.0.16

            composer selfupdate
            composer global require hirak/prestissimo
            composer install --dev --no-interaction -o

            sh ./eccube_install.sh mysql

            php app/console plugin:develop install --path=~/$PLUGIN_CODE.tar.gz
            php app/console plugin:develop enable --code=$PLUGIN_CODE
